spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            clientId: 885924871941554186
            clientSecret: exhpfjpHhTSpMNTg8R9QnWDI_2IxB3G-
            redirectUri: "{baseUrl}/login/oauth2/code/discord"
            scope:
              - identify
              - email
              - guilds
            authorizationGrantType: authorization_code
        provider:
          discord:
            authorizationUri: https://discord.com/api/oauth2/authorize
            tokenUri: https://discord.com/api/oauth2/token
            userInfoUri: https://discord.com/api/users/@me
            userNameAttribute: username
